package com.example.cauldroncolors.data;

import com.example.cauldroncolors.CauldronColors;
import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;

public class CauldronColorsModelProvider extends FabricModelProvider {

    public CauldronColorsModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators blockModelGenerators) {
        blockModelGenerators.createTrivialCube(CauldronColors.WHITE_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.ORANGE_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.MAGENTA_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.LIGHT_BLUE_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.YELLOW_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.LIME_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.PINK_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.GRAY_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.LIGHT_GRAY_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.CYAN_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.PURPLE_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.BLUE_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.BROWN_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.GREEN_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.RED_EGG_BLOCK);
        blockModelGenerators.createTrivialCube(CauldronColors.BLACK_EGG_BLOCK);
    }

    @Override
    public void generateItemModels(ItemModelGenerators itemModelGenerators) {
        // Block item definitions are generated by createTrivialCube.
    }
}